### ISSUE TITLE
Setting cooperativeGestures on MapboxMap

### ISSUE THREAD

**Issue by sweetroll** [studiometa/vue-mapbox-gl#108]
Cooperative Gestures and perhaps some other newer options are missing from the MapboxMap props declarations. Could this be added or perhaps allow the developer to pass any options they like to reduce work on your side?

Thanks

**Comment by titouanmathis** [comment]
This has been fixed in [v2.2.0](https://github.com/studiometa/vue-mapbox-gl/releases/tag/2.2.0).
