### ISSUE TITLE
Add support for `GeolocateControl`

### ISSUE THREAD

**Issue by hacknug** [studiometa/vue-mapbox-gl#11]
Custom use it's pretty straight forward but it would be great if it was available as a component and it dealt with everything like `MapboxNavigationControl` does.

https://docs.mapbox.com/mapbox-gl-js/api/#geolocatecontrol

**Comment by titouanmathis** [comment]
Hi, 

It would be a nice addition, I'll add it to our roadmap.

**Comment by titouanmathis** [comment]
Hi @hacknug, this feature is now on the `develop` branch, it is due to be released in a few days, I will keep you updated in this issue.

**Comment by FrankySnow** [comment]
Hi, are there any plans for releasing it ? This is the component that I am missing currently. Thanks for the good work !

**Comment by titouanmathis** [comment]
Hi @FrankySnow, thanks for your comment 🙂 

The release is planned for this week, I'll keep you updated in this thread.

**Comment by titouanmathis** [comment]
The `MapboxGeolocateControl` component has been released in [v1.3.0](https://github.com/studiometa/vue-mapbox-gl/releases/tag/1.3.0), check out the [documentation](https://vue-mapbox-gl.meta.fr/components/MapboxGeolocateControl.html) for details on how to use it.
