### ISSUE TITLE
Working example for GeoJSON Line with MapboxSource & MapboxLayer

### ISSUE THREAD

**Issue by tony-nz** [studiometa/vue-mapbox-gl#114]
Hey,

I've been trying to get the following working:

https://docs.mapbox.com/mapbox-gl-js/example/geojson-line/

Here is a codesandbox with my attempt so far:

https://codesandbox.io/s/hopeful-christian-7nqqkm

Any ideas?

**Comment by perruche** [comment]
Hello @tony-nz ,

Here is a codesandbox with the GEOJSON route displaying on the map
https://codesandbox.io/s/fast-dream-6nyj29

Changes were small : 
- MapboxLayer needs an id prop
- Making MapboxLayer & MapboxSource siblings and not parent child
- Using 6 number for the hex color

i hope this help
