### ISSUE TITLE
Add the missing clusterProperties to clusters

### ISSUE THREAD

**Issue by gvinson** [studiometa/vue-mapbox-gl#117]
This one is simple. It looks like `clusterProperties` got missed when implementing the props. I've forked this locally and modified the compiled code but do not have access to the individual components. So, here is my suggestion:

In `vue-mapbox-gl/components/MapboxCluster.vue`, add this new prop:
```
clusterProperties: {
		type: Object,
		default: null,
},
```
In the `MapboxCluster` `setup` function, I had to also extract and return the newly added prop, like this:
```
const { data, clusterMaxZoom, clusterRadius, clusterProperties, } = props;
return {
	type: "geojson",
	cluster: true,
	data,
	clusterMaxZoom,
	clusterRadius,
	clusterProperties,
};
```
Vue may handle this automatically, I'm not sure.

Thats it. Now, we can set custom properties to use in our cluster styling. I used this to color clusters differently based on if one of the markers inside has an "alert" tied to it.

**Comment by titouanmathis** [comment]
This has been fixed in [v2.2.0](https://github.com/studiometa/vue-mapbox-gl/releases/tag/2.2.0).
