### ISSUE TITLE
Add support for "visualizePitch" option in MapboxNavigationControl

### ISSUE THREAD

**Issue by FrankySnow** [studiometa/vue-mapbox-gl#15]
Hi,
the prop `visualizePitch` in MapboxNavigationControl is missing.

It would be great to add it, or to provide a generic `options` prop to allow for options that are not yet implemented to be used (the same strategy chosen in MapboxGeocoder).

Link : https://docs.mapbox.com/mapbox-gl-js/api/markers/#navigationcontrol

Thanks !

**Comment by titouanmathis** [comment]
I added the missing props in #16 🙂  

I will try to find a good way to allow usage of not yet implemented props in a future release.

**Comment by titouanmathis** [comment]
Added in [v1.3.0](https://github.com/studiometa/vue-mapbox-gl/releases/tag/1.3.0), available for download now 😉

**Comment by FrankySnow** [comment]
That was quick, thanks !
