### ISSUE TITLE
MapboxGeolocateControl not exported into build

### ISSUE THREAD

**Issue by FrankySnow** [studiometa/vue-mapbox-gl#18]
Hello,
the new `MapboxGeolocateControl` is not exported from the `src/components/index.js` file, so it is not available in the last build (1.3.1). I don't know enough Vuepress to understand why the demo is working,

Btw, thanks for all the updates you made these last days !

**Comment by perruche** [comment]
Hi, 

Will open a hotfix to resolve this issue.

FYI this is working inside Vuepress because the components are registered inside the config.js file line 46 which is resolving all the files of the src/components folder

```js
plugins: [
    [
      '@vuepress/register-components',
      {
        componentsDir: resolve(__dirname, '../../src/components'),
      },
    ],
  ],
```

**Comment by perruche** [comment]
New release 1.3.2 is now available on npm.

**Comment by FrankySnow** [comment]
Thanks a lot for the fix and the explanation !
