### ISSUE TITLE
Add the ability to programmatically trigger a Geolocation with MapboxGeolocateControl

### ISSUE THREAD

**Issue by FrankySnow** [studiometa/vue-mapbox-gl#19]
Hi,
it would be useful to implement the `trigger()` method of the GeolocateControl (https://docs.mapbox.com/mapbox-gl-js/api/markers/#geolocatecontrol#trigger) in the MapboxGeolocateControl component.

We could provide a way to access the Control instance outside of the component, just like we can [access the Mapbox instance via ~~@mb-ready~~ @mb-created](https://vue-mapbox-gl.meta.fr/components/mapboxmap.html#accessing-the-mapbox-instance). Alternatively, maybe that a prop could do the job.

Thanks in advance for taking this into consideration !

**Comment by titouanmathis** [comment]
Hey @FrankySnow, sorry for the late reply, and (again) thanks for the suggestion! 

This will be possible in the upcoming v2, the instance of the control will be exposed by the component:

```vue
<script setup>
  import { ref, unref } from 'vue';
  import { MapboxMap, MapboxGeolocateControl } from '@studiometa/vue-mapbox-gl';

  const geolocate = ref();
  
  function trigger() {
    if (unref(geolocate)) {
      unref(geolocate).control.trigger();
    }
  }
</script>

<template>
  <MapboxMap>
    <MapboxGeolocateControl ref="geolocate" />
  </MapboxMap>
  <button type="button" @click="trigger" :disabled="!geolocate">
    Geolocate me!
  </button>
</template>
```
