### ISSUE TITLE
Replace @mb-ready with @mb-created in the docs for MapboxMap

### ISSUE THREAD

**Issue by FrankySnow** [studiometa/vue-mapbox-gl#20]
Hello,
the docs for MapboxMap mention a @mb-ready event that is not fired, the right one is @mb-created.

https://vue-mapbox-gl.meta.fr/components/MapboxMap.html#accessing-the-mapbox-instance

**Comment by titouanmathis** [comment]
Fixed in [v1.3.3](https://github.com/studiometa/vue-mapbox-gl/releases/tag/1.3.3)!
