### ISSUE TITLE
Add @mb-clear event in MapboxGeocoder

### ISSUE THREAD

**Issue by FrankySnow** [studiometa/vue-mapbox-gl#23]
Hello,
according to [the docs for mapbox-gl-geooder](https://github.com/mapbox/mapbox-gl-geocoder/blob/master/API.md#parameters-18), there is a `clear` event that is "Emitted when the input is cleared".

That would translate to a `@mb-clear` event for this component. Could you please add it in a next release ?

Thanks for taking this into consideration

**Comment by titouanmathis** [comment]
Hey @FrankySnow, sorry for the late reply, and thanks for the suggestion! This will be available in the upcoming v2.

**Comment by FrankySnow** [comment]
Happy to read that, thank you !
