### ISSUE TITLE
Duplicate install way

### ISSUE THREAD

**Issue by vduggen-velo** [studiometa/vue-mapbox-gl#28]
Think you meant yarn or npm

![image](https://user-images.githubusercontent.com/74964843/107413110-2119d080-6aef-11eb-9b24-9ec124e9d073.png)

**Comment by titouanmathis** [comment]
Thanks for the heads-up, it has been fixed in the [v1.4.7](https://github.com/studiometa/vue-mapbox-gl/releases/tag/1.4.7)!
