### ISSUE TITLE
Vue 3 compatibilty

### ISSUE THREAD

**Issue by FrankySnow** [studiometa/vue-mapbox-gl#29]
Hi, 
is the library already compatible with Vue 3 ? 
If not, are there any plans on supporting Vue 3 ?
Thanks !

**Comment by titouanmathis** [comment]
Hello @FrankySnow,

Vue 3 support is not planned yet on our side, in the meantime you can use the [vue-2-3 package](https://github.com/privatenumber/vue-2-3) to use some [basic functionality](https://codepen.io/titouanmathis/pen/qBqxpEV).

I will re-open and update this issue when we have news on the subject.

**Comment by FrankySnow** [comment]
Interesting, thank you for the Codepen.
