### ISSUE TITLE
Mapbox Cluster

### ISSUE THREAD

**Issue by VeronikaBalter** [studiometa/vue-mapbox-gl#41]
did not find an example of a custom Mapbox Cluster, is it possible to do this?

**Comment by titouanmathis** [comment]
There are some examples in our [documentation](https://vue-mapbox-gl.meta.fr/components/MapboxCluster.html) on how to use the `MapboxCluster` component. You can also have a look at the examples from the Mapbox documentation on how to configure your layers:

- [Display HTML clusters with custom properties](https://docs.mapbox.com/mapbox-gl-js/example/cluster-html/)
- [Create and style clusters](https://docs.mapbox.com/mapbox-gl-js/example/cluster/)

The `MapboxCluster` component might have some limitation for complex scenarios. In this case, you will need to implement the cluster logic by hand with the `MapboxSource` and `MapboxLayer` components (as in the `MapboxCluster` component, see its [sources](https://github.com/studiometa/vue-mapbox-gl/blob/master/src/components/MapboxCluster.vue#L3-L20)).
