### ISSUE TITLE
Consider merging with the v-mapbox project

### ISSUE THREAD

**Issue by delebash** [studiometa/vue-mapbox-gl#42]
Both of these projects are trying to accomplish the same thing using vue.  I think it would be much more beneficial to have more devs working on one project then split between two that accomplish the same goal. Just a thought. Ty

v-mapbox project https://github.com/geospoc/v-mapbox

**Comment by titouanmathis** [comment]
Thanks for the suggestion @delebash. This package does not aim to become a reference for using Mapbox GL in Vue, it is an internal tool that we thought could benefit others.

I am not considering merging it with v-mapbox for now, as this is a tool that we still use for our projects from time to time.
