### ISSUE TITLE
Add @md-click events to MapboxMarker

### ISSUE THREAD

**Issue by vjanssens** [studiometa/vue-mapbox-gl#57]
I'd like to pan and zoom the map to a marker once a marker is clicked. I've tried to add `@md-click` and `@click` to the `MapboxMarker` components to perform these actions manually, but these events are not triggered by the child component.

Would this be as simple as adding 'click' to https://github.com/studiometa/vue-mapbox-gl/blob/master/packages/vue-mapbox-gl/components/MapboxMarker.vue#L76 ?

**Comment by perruche** [comment]
Hi,

`click` is not a supported event on the `Marker` class from mapbox-gl [see](https://docs.mapbox.com/mapbox-gl-js/api/markers/#marker-events). 

You can achieve this behavior using `MapboxLayer` and `MapboxSource` components. who supports click events 

```
<script setup>
<script setup>
  import { MapboxMap, MapboxSource, MapboxLayer } from '@studiometa/vue-mapbox-gl';
  import { gsap } from 'gsap';

  let pitch = ref(0);
  let bearing = ref(0);

  const sourceOptions = {
    type: 'geojson',
    data: {
      type: 'FeatureCollection',
      features: [
        {
          type: 'Feature',
          properties: {},
          geometry: {
            type: 'Point',
            coordinates: [-95.225, 47.254],
          }
        },
      ]
    }
  };

  const layerOptions = {
    id: 'circle',
    type: 'circle',
    source: 'markers', // use the id attribute from MapboxSource component
    paint: {
      'circle-color': '#4264fb',
      'circle-radius': 8,
      'circle-stroke-width': 2,
      'circle-stroke-color': '#ffffff'
    }
  };

  function onLayerClick(event) {
    gsap.to(bearing, {
      value: 10,
      duration: 2
    });
    gsap.to(pitch, {
      value: 70,
      duration: 2
    });
  }
</script>

<template>
  <MapboxMap
    class="w-screen h-screen fixed inset-0 z-goku"
    access-token="..."
    map-style="..."
    :center="[-95.225, 47.254]"
    :zoom="12"
    :pitch="pitch"
    :bearing="bearing">
    <MapboxSource id="markers" :options="sourceOptions" />
    <MapboxLayer
      id="markers-layer"
      :options="layerOptions"
      @mb-click="onLayerClick" />
  </MapboxMap>
</template>
```

Hope this helps

**Comment by vjanssens** [comment]
Thanks @perruche for the information and the code examples. The `@click` event handler did work on the previous vue-mapbox-gl version, hence why I asked it here as well. I understand that was from a different developer, so i'll close this issue for now.
