### ISSUE TITLE
Get user current location coordinates

### ISSUE THREAD

**Issue by boring-dragon** [studiometa/vue-mapbox-gl#66]
Is there a way to get current user location coordinates when it updated by `MapboxGeolocateControl`

**Comment by JuanRoodt** [comment]
Good day man, I did the below with vue2 but can easily be converted to vue 3 composition api to ,

 <MapboxGeolocateControl  :trackUserLocation="true" @mb-trackuserlocationstart="myLocationStart"/>

        myLocationStart() {      

            navigator.geolocation.getCurrentPosition(position => {
                const {latitude, longitude} = position.coords;
                this.order.long = longitude;
                this.order.lat = latitude;
                this.geocodeLatLng(latitude, longitude);
            });
  },

        geocodeLatLng(latitude, longitude) {
            let geocoder = new google.maps.Geocoder;
            let latlng = {lat: parseInt(latitude), lng: parseInt(longitude)};

            geocoder.geocode({'location': latlng}, (results, status) => {
                if (status === 'OK') {
                    if (results[1]) {
                        this.order.address = results[1]['formatted_address']
                        this.address = results[1]['formatted_address']
                    }
                }
            });


// you just need to stop user tracking afterwards, else the map might move around slightly

**Comment by JuanRoodt** [comment]
Good day,



Get the location with the below:
     // in your template
     <MapboxGeolocateControl v-if="!location"
                                    :trackUserLocation="true"
                                    @mb-trackuserlocationstart="myLocationStart"/>

    // between your script tags
import {ref} from 'vue'

let lat = ref(null);
let lng= ref(null);

const myLocationStart = ()=>{
            navigator.geolocation.getCurrentPosition(position => {
                const {latitude, longitude} = position.coords;
                lng = longitude;
                lat = latitude;
            });
}

// maby use a while loop to run the function every x minutes after the stored values doesn't equal null, if the lat and lng do not equal the stored lat and long execute your function.

**Comment by titouanmathis** [comment]
In addition to @JuanRoodt answer, VueUse has a `useGeolocation` function which will use the browser API to get the current user location: https://vueuse.org/core/usegeolocation/#usegeolocation.
