### ISSUE TITLE
Draggend

### ISSUE THREAD

**Issue by JuanRoodt** [studiometa/vue-mapbox-gl#72]
Good day,

Is there a way to access the marker location after draggend? I get the event to trigger with the below code, but can't seem to access the markers new location. I have access to the current location via Vue dev tools but it is set according to my manual geo or my address geocode lat lng.

@mb-dragend='markerMoved'

const markerMoved = () => {
console.log('moved');
}

**Comment by titouanmathis** [comment]
You should have access to the `Marker` instance inside the `markerMoved` function. You can then get its location with the `getLngLat()` method: 

```js
const markerMoved = (marker) => {
  const latLng = marker.getLngLat();
};
```

See https://docs.mapbox.com/mapbox-gl-js/api/markers/#marker-instance-members for reference.

**Comment by JuanRoodt** [comment]
Thanks @titouanmathis, you got me on the right track. In the end, I had to use:

`
const markerMoved = (marker) => {
    const latLng = marker.target._lngLat
}
`

**Comment by mccombs** [comment]
@JuanRoodt - just wanted to say thank you. The docs need to include this as an example.
