### ISSUE TITLE
MapboxGeocoder does not emit `mb-created`

### ISSUE THREAD

**Issue by ralphschindler** [studiometa/vue-mapbox-gl#76]
The geocoder does not emit the created event with the instance of the geocoder.

**Comment by titouanmathis** [comment]
The `MapboxGeocoder` instance is exposed (see [doc](https://vuejs.org/api/options-state.html#expose)) via a `control` key: 

https://github.com/studiometa/vue-mapbox-gl/blob/develop/packages/vue-mapbox-gl/components/MapboxGeocoder.vue#L186

You can access it with something like the following:

```vue
<script setup>
  import { ref, watch } from 'vue';
  import MapboxGeocoder from '@mapbox/mapbox-gl-geocoder';
 
  const geocoder = ref();

  watch(geocoder, (value) => {
    if (value?.control) {
      console.log(value.control instanceof MapboxGeocoder); // true
    }
  });
</script>

<template>
  <mapbox-map>
    <mapbox-geocoder ref="geocoder" />
  </mapbox-map>
</template>
```
