### ISSUE TITLE
The map is not zooming on the new bounds when a default center is given

### ISSUE THREAD

**Issue by michaelklopf** [studiometa/vue-mapbox-gl#90]
We have a problem that when given a default center, that fitBounds does not zoom to the area with the given bounds and the new center of those bounds.

We set up the map according to the docs

```vue
    <MapboxMap 
         :access-token="token" 
         :center="[10.16493, 50.00602]" 
         :zoom="6" 
         map-style="mapbox://styles/mapbox/streets-v11" 
         @mb-created="(mapboxInstance) => map = mapboxInstance" 
         @mb-load="adjustBounds"
    >
        <MapboxMarker v-for="place in places" :key="place" :lng-lat="[place.longitude, place.latitude]" />
    </MapboxMap>
```

This is the code that should fit the map to the new bounds
```js
const map = ref();

watch(
    () => props.places,
    () => {
        adjustBounds();
    }
);

const adjustBounds = () => {
    if (props.places.length === 0) {
        return;
    }

    let bounds = new Mapbox.LngLatBounds();

    for (const place of props.places) {
        bounds.extend([place.longitude, place.latitude]);
    }

    map.value.fitBounds(bounds, {
        padding: 50,
        duration: 3000,
    });
};
```

We debugged a little and the fitBounds function returns a new map object but with the default center set above, not with the new one internally computed. The nw and se boundaries of the map are new, but the center is not. Hence the map is showing the markers in a section of the map, but it stays focused on the default center and doesn't zoom.

Has anyone an example how he adjust the bounds with a given set of places returned form a search?

**Comment by michaelklopf** [comment]
Ok, after a lot of trial and error, it appears that the center must be a ref. 

```vue
    <MapboxMap 
         :access-token="token" 
         :center="center" 
```

```js
/* other code */
    map.value.fitBounds(bounds, {
        padding: 50,
        duration: 3000,
    });
};

let center = ref([10.16493, 50.00602]);
```

The vue dev tools show that the attribute `originCoordinates` is not changing when center is not a ref. Is that attribute based on the center variable and when it's no ref, it cannot update the map?

**Comment by michaelklopf** [comment]
I added an PR https://github.com/studiometa/vue-mapbox-gl/pull/95

**Comment by titouanmathis** [comment]
Thanks for the PR @michaelklopf, this will be released in the next version of the doc.
