### ISSUE TITLE
Cannot read properties of undefined (reading 'addTo')

### ISSUE THREAD

**Issue by omaritoml** [studiometa/vue-mapbox-gl#91]
This is my code. I'm getting this error. Cannot read properties of undefined (reading 'addTo')

```
<template>

            <MapboxGeocoder 
              :access-token="mapbox_token"
              :types="'address'"
              :country="'us'"
              :proximity="[-122.3995752 , 37.7881856]"
              map-style="mapbox://styles/mapbox/streets-v11"
              @mb-created="instance => control = instance"
              @mb-result="addAddress($event)"/>
 
</template>


<script>

    import { ref } from 'vue'
    import { MapboxMap, MapboxGeocoder } from '@studiometa/vue-mapbox-gl';
    import '@mapbox/mapbox-gl-geocoder/lib/mapbox-gl-geocoder.css';
   

    export default {
    
    components: {
        MapboxMap,
        MapboxGeocoder
    },
    props: {
      
    },
    emits: [
        'AddressSelected'
    ],  
    setup(props, {emit}){
        const control = ref();
        const mapbox_token = process.env.MIX_MAPBOX_SECRET
        const addAddress = (data) => { 
            emit('AddressSelected', data.result)
        }

        return{
            mapbox_token,
            control,
            addAddress
        }
    },

    }

    </script>
```

**Comment by titouanmathis** [comment]
Hi @omaritoml, could you send me a link to a reproduction on Stackblitz?

**Comment by Niiidro** [comment]
Hello @titouanmathis.

I have the same Error and also found this Error on your Website:
https://vue-mapbox-gl.studiometa.dev/components/mapboxgeocoder/#examples

Looks like the Problem comes  when you use the Geolocator without Map. Hope this helps

**Comment by agracia-foticos** [comment]
Same issue

In your page also fails

![image](https://user-images.githubusercontent.com/77386602/221142786-59b346bb-405f-4154-94db-7a550b3ec311.png)

In our page

![image](https://user-images.githubusercontent.com/77386602/221142866-31301e7b-83cf-4722-92fc-00dc5a6f6e95.png)

**Comment by titouanmathis** [comment]
Thanks for the precisions, I will look into this issue next week.
