### ISSUE TITLE
Custom markers icon

### ISSUE THREAD

**Issue by britlog** [studiometa/vue-mapbox-gl#94]
Hi,

I read the doc but can't find how to customize markers icon.
I first tried with the MapboxImage component but impossible to link the id with the MapboxMarker component.
I then tried to pass a custom element props in MapboxMarker component but all my markers appeared stacked in one place (I have a v-for in MapboxMarker component to set lng-lat props).

Do you please have some working exemples ?

Best regards

**Comment by perruche** [comment]
Hi @britlog,

You can use the exemple provided in the documentation with [custom HTML]( https://vue-mapbox-gl.studiometa.dev/components/mapboxmarker/#custom-html)

```vue
<script setup>
  import { MapboxMap, MapboxMarker } from '@studiometa/vue-mapbox-gl';
</script>

<template>
  <MapboxMap
    style="height: 400px"
    :access-token="MAPBOX_API_KEY"
    map-style="mapbox://styles/mapbox/streets-v11"
    :center="[0, 0]"
    :zoom="1">
    <MapboxMarker :lng-lat="[0, 0]">
      <img src="PATH_TO_FILE" width="16" height="16">
    </MapboxMarker>
  </MapboxMap>
</template>
```

Hope this helps

**Comment by britlog** [comment]
Hi @perruche, Thanks it works like a charm !
