### ISSUE TITLE
Geocoder does not search for roads/streets

### ISSUE THREAD

**Issue by McFege** [studiometa/vue-mapbox-gl#96]
The current Geocoder Implementation does not allow for any results to be displayed, more detailed than locality. Please make it possible to adjust this setting or allow streets to be searchable as well! As documented in [https://docs.mapbox.com/api/search/geocoding/](https://docs.mapbox.com/api/search/geocoding/)!

**Comment by titouanmathis** [comment]
Hi @McFege, you can define the types of data you want to search for with the geocoder component with its [`types` props](https://vue-mapbox-gl.studiometa.dev/components/MapboxGeocoder/#types). It is mapped to the [`options.types` parameter](https://github.com/mapbox/mapbox-gl-geocoder/blob/main/API.md#parameters) of the MapboxGeocoder constructor.

If this does not fix your issue, please provide a detailed demo of the bug.
