### ISSUE TITLE
please Add support for right-to-left scripts 

### ISSUE THREAD

**Issue by firaskanaan93** [studiometa/vue-mapbox-gl#97]
![image](https://user-images.githubusercontent.com/75640807/230561693-9fccb98a-3236-4e49-bb4f-01df7dc54d5f.png)
https://docs.mapbox.com/mapbox-gl-js/example/mapbox-gl-rtl-text/

**Comment by titouanmathis** [comment]
Hi @firaskanaan93, this is something that you can already complete by importing the plugin in your component:

```vue
<script setup>
  import { onMounted } from 'vue';
  import mapboxgl from 'mapbox-gl';
  import rtlPlugin from '@mapbox/mapbox-gl-rtl-text/mapbox-gl-rtl-text.js?url';

  let rtlPluginIsInstalled = false;
  onMounted(() => {
    if (!rtlPluginIsInstalled) {
      rtlPluginIsInstalled = true;
      mapboxgl.setRTLTextPlugin(rtlPlugin);
    }
  });
</script>
```

See the running demo on Stackblitz: https://stackblitz.com/edit/github-jbfwmb-bvruv3?file=app.vue.
